language: java
jdk: oraclejdk8
script: mvn clean install -B
addons:
  ssh_known_hosts:
    - 207.154.240.205
  - lemmeknow.tk
branches:
  only:
  - master
env:
  global:
  - REMOTEAPPDIR=/home/deploy/nc-project
  - REMOTEUSER=deploy
  - REMOTEHOST=207.154.240.205
before_install:
- openssl aes-256-cbc -K $encrypted_2c9f86b9c344_key -iv $encrypted_2c9f86b9c344_iv
  -in deploy.enc -out deploy -d
before_script:
- chmod 600 deploy && mv deploy ~/.ssh/id_rsa
after_success:
- "./scripts/deploy.sh"
